language: python
python:
  - "3.6"

before_install:
  - git clone -b development https://github.com/clips/pattern.git
  - pushd pattern
  - python setup.py install
  - popd

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - pytest test/
